### ISSUE TITLE
Памылка распазнаваньня: карожыццл

### ISSUE THREAD

**Issue by 375gnu** [verbumby/slouniki#1]
Каро́віцца брыдзіцца, Гідзіцца’ (Яўе.), да карожыцц**л** (Гл.) пад уплывам [карова](https://verbum.by/esbm/karova).
https://verbum.by/esbm/karovicca

Мусіць быць **-а**

**Comment by ramanenka** [comment]
@375gnu выпраўлена, дзякуй!
